name: contact_list
version: 0.0.3
description: 
author: Jim Washington <washington.jim@gmail.com>
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: "^2.0.0-beta.17"
  browser: '^0.10.0+2'
  angular2_rbi: '^0.0.3'
  uuid: any
  dart_to_js_script_rewriter: ^1.0.0
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
dev_dependencies:
  grinder: '^0.8.0+1'
